name: portfolio_flutter_web
description: "Portfolio of Muhammad Zakaullah"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State management
  flutter_riverpod: ^2.6.1

  # routing
  go_router: ^16.1.0

  # URL launcher for opening external links
  url_launcher: ^6.3.1
  
  # URL strategy for web routing
  url_strategy: ^0.2.0
  
  # PDF viewer
  pdfrx: ^2.1.5
  html: ^0.15.6
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_gen_runner: ^5.10.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/projects/
    - assets/projects/DhaoAI - Mobile App/
    - assets/projects/DhaoAI - Mobile App/dark/
    - assets/projects/DhaoAI - Mobile App/light/
    - assets/projects/laaf/
    - assets/projects/laaf/dark/
    - assets/projects/laaf/light/
    - assets/projects/MyVox/
    - assets/projects/NewImage/
    - assets/projects/Roomph/
    - assets/projects/TapPay/
    - assets/Muhammad-Zakaullah-Resume-Mobile-developer.pdf
    # - assets/Muhammad-Zakaullah-Resume.pdf

# dart run build_runner build --build-filter="lib/assets/**" --build-filter="pubspec.yaml"
# for only limiting to 
flutter_gen:
  output: lib/gen/
  line_length: 80

  assets:
    exclude:
      - assets/projects/**/summary.txt
      - pubspec.yaml

  integrations:
    image: true
    flutter_svg: true
    rive: false
    lottie: false
